//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_GUI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIA_NCC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DANHGIA_NCC()
        {
            this.DanhGiaNCC_SPDMH = new HashSet<DanhGiaNCC_SPDMH>();
        }
    
        public string MaDGNCC { get; set; }
        public string MaNV { get; set; }
        public string MaNCC { get; set; }
        public Nullable<System.DateTime> NgayDanhGia { get; set; }
        public Nullable<double> DiemChatLuong { get; set; }
        public Nullable<double> DiemGiaCa { get; set; }
        public Nullable<double> DiemHieuQua { get; set; }
        public string MucDoDanhGia { get; set; }
        public string TieuChiDanhGia { get; set; }
    
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaNCC_SPDMH> DanhGiaNCC_SPDMH { get; set; }
    }
}
