//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_GUI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANCONG_CONGVIEC
    {
        public string MaPC { get; set; }
        public string MaNV { get; set; }
        public System.DateTime NgayGiao { get; set; }
        public System.DateTime NgayHT { get; set; }
        public string Congviec { get; set; }
        public string TThai { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
