//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAOGIA()
        {
            this.CT_BAOGIA = new HashSet<CT_BAOGIA>();
        }
    
        public string MaBG { get; set; }
        public string MaNCC { get; set; }
        public Nullable<System.DateTime> NgayBG { get; set; }
    
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_BAOGIA> CT_BAOGIA { get; set; }
    }
}
