//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIA_SANPHAM
    {
        public string MaDGSP { get; set; }
        public string MaSP { get; set; }
        public string KetQua { get; set; }
        public Nullable<System.DateTime> NgayDG { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
