//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaNCC_SPDMH
    {
        public string MaDGNCC { get; set; }
        public string MaDGSP { get; set; }
        public string ChuThich { get; set; }
    
        public virtual DANHGIA_NCC DANHGIA_NCC { get; set; }
        public virtual DANHGIASP_TRONGDON DANHGIASP_TRONGDON { get; set; }
    }
}
