//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONMUAHANG
    {
        public string MaDMH { get; set; }
        public System.DateTime NgayLap { get; set; }
        public string MaHD { get; set; }
        public string MaNV { get; set; }
        public string MaNCC { get; set; }
        public string TThai { get; set; }
        public string MoTa { get; set; }
    
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual HOPDONGMH HOPDONGMH { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
