//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAILIEU
    {
        public string MaTL { get; set; }
        public string LoaiTL { get; set; }
        public string MaNV { get; set; }
        public System.DateTime NgayGui { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
