//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHTOAN
    {
        public string MaTT { get; set; }
        public int MaHD { get; set; }
        public Nullable<System.DateTime> NgayTT { get; set; }
        public string TrangThai { get; set; }
    
        public virtual HOADON HOADON { get; set; }
    }
}
